# Default values for phoenix-trackings-api
# This file is in YAML format
# Declared variables to be passed into $/templates files

appName: tracking-api
namespace: phoenix-qa

image:
  repository: 889859566884.dkr.ecr.us-east-1.amazonaws.com/phoenix-tracking-api
  tag: qa
  pullPolicy: Always

imagePullSecrets: []

service:
  type: NodePort
  port: 80

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "true"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# replicacount has no impact if autoscaling.enabled = true
replicacount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 85

dns:
  internal: dev.sgp.private.wiley.host
  external: dev.sgp.wiley.host

env_vars:
  data:
    LOG_JSON: "true"
    LOG_MINIMUMLEVEL: Information
    MONGO_DB_NAME: phoenix-tracking-api-nonprod
    MONGO_TLS_CA_FILE_PATH: "/cert/global-bundle.pem"
    USERS_API_BASE_URL: "http://users-api"
    COMPANY_API_BASE_URL: "http://company-api"
    CONTENT_API_BASE_URL: "http://contents-api"
    ENROLLMENT_API_BASE_URL: "http://enrollments-api"
    ENTITLEMENT_API_BASE_URL: "http://entitlements-api"
    KEYCLOAK_BASE_URL: "https://keycloak.dev.sgp.wiley.host"
    KEYCLOAK_REALM: "phoenix"
    KEYCLOAK_AUDIENCE: "account"
    OPA_BASE_URL: "http://opa/"
    KAFKA_HOST: "b-1.eksnonprodus.rsck18.c20.kafka.us-east-1.amazonaws.com:9092,b-2.eksnonprodus.rsck18.c20.kafka.us-east-1.amazonaws.com:9092"
    KAFKA_TOPIC: "ck-phoenix-tracking"

externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-nonprod-us-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: dev/eks/phoenix
    nameValue: USERS_API_KEY
    propertyValue: USERS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: COMPANY_API_KEY
    propertyValue: COMPANY_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: CONTENTS_API_KEY
    propertyValue: CONTENTS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: ENROLLMENTS_API_KEY
    propertyValue: ENROLLMENTS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: ENTITLEMENTS_API_KEY
    propertyValue: ENTITLEMENTS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: API_KEY
    propertyValue: TRACKINGS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: MONGO_CONNECTION_STRING
    propertyValue: TRACKINGS_API_NONPROD_MONGO_CONNECTION_STRING
